### ISSUE TITLE
Cannot create ReportDefinition

### ISSUE THREAD

**Issue by vhtien** [martiner/gooddata-java#359]
Get error when using constructor `AttributeInGrid(String uri)`

version: 2.0.0.RC-1

trace:
com.gooddata.GoodDataRestException: 400: [requestId=gx3w92bwI9gtvkYA:dte6j4tr1xgu0yam] Checking 'reportDefinition', result STRUCTURE INVALID - name of structure:'ReportDefinition'(tag:reportDefinition),  /reportDefinition/content/grid/ReportGrid: Object  does not match any alternative. Alternatives tried : [STRUCTURE INVALID - name of structure:'ReportDefinition'(tag:reportDefinition),  /reportDefinition/content/grid/ReportGrid/case:/URI: Missing tag 'uri'., STRUCTURE INVALID - name of structure:'ReportDefinition'(tag:reportDefinition),  /reportDefinition/content/grid/ReportGrid/case:/GridContent/rows/<list:1>/GridElement: Object  does not match any alternative. Alternatives tried : [STRUCTURE INVALID - name of structure:'ReportDefinition'(tag:reportDefinition),  /reportDefinition/content/grid/ReportGrid/case:/GridContent/rows/<list:1>/GridElement/case:: You used array, object or hash. Constant 'metricGroup' expected., STRUCTURE INVALID - name of structure:'ReportDefinition'(tag:reportDefinition),  /reportDefinition/content/grid/ReportGrid/case:/GridContent/rows/<list:1>/GridElement/case:/AttributeInGrid/attribute: Key 'alias' is compulsory.]]

**Comment by vhtien** [comment]
Get another error when using constructor `AttributeInGrid(DisplayForm)`

version: 2.0.0.RC-1

trace:
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.currentToken()Lcom/fasterxml/jackson/core/JsonToken;
	at com.gooddata.md.report.GridElementDeserializer.deserialize(GridElementDeserializer.java:22)
	at com.gooddata.md.report.GridElementDeserializer.deserialize(GridElementDeserializer.java:18)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)

More info: https://ci.intgdc.com/job/Core-Graphene-project-partial-export-import/184/artifact/ui-tests-core/target/failures/PartialExportAndImportProjectTest.partialExportAndImportReport/stacktrace.txt

**Comment by jimirocks** [comment]
regarding usage `AttributeInGrid(DisplayForm)` you probably forces too old jackson version on your classpath, because [currentToken method](https://fasterxml.github.io/jackson-core/javadoc/2.8/com/fasterxml/jackson/core/JsonParser.html#currentToken()) exists since jackson 2.8.0

**Comment by jimirocks** [comment]
Well, it seems `alias` must be set both for `AttributeInGrid` and `MetricElement` - so we should remove constructors creating `null` `alias`.

This affects the 1.X.X versions as well.

**Comment by jimirocks** [comment]
fixed by #362
